### ISSUE TITLE
Shortcode shortcomings

### ISSUE THREAD

**Issue by fbruetting** [getzola/zola#659] opened 2019-04-09 00:41 UTC
# Bug Report

## Environment

Zola version: v0.6.0

## Expected Behavior
I’d like to use shortcodes with indentation, so that it fits nicely in my code. If this is not possible, It would be cool if we could get compilation errors in the command line, instead of corrupted output.

## Current Behavior
Every time when I indent shortcodes, I get very strange behavior. This means that the shortcode introduces things like `</code></pre>` blocks and cryptic encoded characters. The latter additionally corrupts the second starting `<div>`, so that one superfluous `</div>` stays as leftover, which is why everything below that line gets weirdly rendered, additionally.

So when I for example place tabs before `{{ <SHORTCODE> }}` in my `_index.md`, I get the following code generated, instead of the correct one further down below:

```html
<div class="galerie">
	<div>
	<a rel="alternate" href=&#x2f;galerie&#x2f;01.jpg>
		<img alt="Bild" src=&#x2f;galerie&#x2f;01.jpg>
	</a>
</div>
<pre><code>&lt;div&gt;
&lt;a rel=&quot;alternate&quot; href=&amp;#x2f;galerie&amp;#x2f;02.jpg&gt;
	&lt;img alt=&quot;Bild&quot; src=&amp;#x2f;galerie&amp;#x2f;02.jpg&gt;
&lt;/a&gt;
</code></pre>
</div>
</div> <!--galerie-->
```

```html
<div class="galerie">
<div>
	<a rel="alternate" href=&#x2f;galerie&#x2f;01.jpg>
		<img alt="Bild" src=&#x2f;galerie&#x2f;01.jpg>
	</a>
</div>
<div>
	<a rel="alternate" href=&#x2f;galerie&#x2f;02.jpg>
		<img alt="Bild" src=&#x2f;galerie&#x2f;02.jpg>
	</a>
</div>
</div> <!--galerie-->
```

Furthermore, is it possible that the output will show up special characters correctly, instead of that ugly encoded style?

**Comment by Keats** [comment] 2019-04-09 08:21
> I’d like to use shortcodes with indentation, so that it fits nicely in my code

The issue with that is that one of the way CommonMark defines code blocks is with indentation which is what is happening there. Shortcodes are rendered before markdown so the inserted HTML can potentially trigger the code block of the markdown parser.

**Comment by fbruetting** [comment] 2019-04-09 08:37
Ok, is then one of the following possible without excessive work?

* Filtering this somehow, i.e. getting CommonMark to not handle shortcodes (and therefore also not handle prepending space), or substracting the indentation and adding it afterwards back.
* Excluding whole lines from the CommonMark parser, when they solely consist of shortcode expressions.
* Trying to catch this case by searching for “indentation before shortcodes” and printing an error.
* Validating the output by a parser and printing a warning, if there is something wrong (missing `<div>` in this case).

**Comment by Keats** [comment] 2019-04-18 07:51
The issue is that the shortcodes rendering is happening before the markdown rendering, the markdown parser only sees some HTML

**Comment by Keats** [comment] 2020-11-27 10:17
I think this is fixed now?

**Closed as completed by Keats** 2020-11-27 10:17 UTC
