### ISSUE TITLE
Rendering bug for headings that contain `!`

### ISSUE THREAD

**Issue by phil-opp** [getzola/zola#42] opened 2017-04-21 11:27 UTC
One of my headings is `## Hello World!!` in markdown. The generated html is:

```html
<h2 id="hello-world"><a class="anchor" href="#hello-world" aria-label="Anchor link for: hello-world">
    🔗
</a>
Hello Worldid=""><a class="anchor" href="#" aria-label="Anchor link for: ">
    🔗
</a>
!id="-1"><a class="anchor" href="#-1" aria-label="Anchor link for: -1">
    🔗
</a>
!</h2>
```

**Comment by Keats** [comment] 2017-04-21 11:32
Does it work if you remove the `!`? If not, can you paste the whole markdown?

The header anchors is by far the hackiest thing in gutenberg so I'm not too surprised it's not working super well sadly.

I'll have a look tomorrow

**Comment by phil-opp** [comment] 2017-04-21 11:36
Yeah, it works fine without the `!`.

Some more test cases:

```md
## Foo
```

```html
<h2 id="foo"><a class="anchor" href="#foo" aria-label="Anchor link for: foo">
    🔗
</a>
Foo</h2>
```

---

```md
## Foo!
```

```html
<h2 id="foo"><a class="anchor" href="#foo" aria-label="Anchor link for: foo">
    🔗
</a>
Fooid=""><a class="anchor" href="#" aria-label="Anchor link for: ">
    🔗
</a>
!</h2>
```

---

```md
## Foo!!!!!
```

```html
<h2 id="foo"><a class="anchor" href="#foo" aria-label="Anchor link for: foo">
    🔗
</a>
Fooid=""><a class="anchor" href="#" aria-label="Anchor link for: ">
    🔗
</a>
!id="-1"><a class="anchor" href="#-1" aria-label="Anchor link for: -1">
    🔗
</a>
!id="-2"><a class="anchor" href="#-2" aria-label="Anchor link for: -2">
    🔗
</a>
!id="-3"><a class="anchor" href="#-3" aria-label="Anchor link for: -3">
    🔗
</a>
!id="-4"><a class="anchor" href="#-4" aria-label="Anchor link for: -4">
    🔗
</a>
!</h2>
```

**Comment by phil-opp** [comment] 2017-04-21 12:25
The problem is that [these lines](https://github.com/Keats/gutenberg/blob/04da527e536fbe6095c9bca816604a58e20b25d4/src/markdown.rs#L202-L211) are executed again for each `!`. So `!` is slugified, which yields the empty string `""`. The empty string is not present in `anchors`, so the first `!` gets `id=""`. The second `!` then gets `id="-1"` , i.e. `""` with an appended `"-1"`  because `id=""` is already taken.

So the question is why the if block is executed twice for the same heading… I assume that it has to do with the `in_header` variable…

**Comment by Keats** [comment] 2017-04-22 02:43
So the issue is that pulldown_cmark sends a separate event for markdown specific characters (`! * ()` etc) like [here](https://github.com/google/pulldown-cmark/blob/master/src/parse.rs#L1233) for the `!`

It's fixed in master, thanks

**Closed as completed by Keats** 2017-04-22 02:43 UTC

**Comment by phil-opp** [comment] 2017-04-25 09:35
Thanks!
