### ISSUE TITLE
Support reStructuredText

### ISSUE THREAD

**Issue by LuoZijun** [getzola/zola#638] opened 2019-03-21 06:42 UTC
Hi, have plan to support reStructuredText ?

A rust lib: https://github.com/flying-sheep/rust-rst

**Comment by Keats** [comment] 2019-03-21 08:58
I don't think this crate is an useable state.

This is a duplicate of https://github.com/getzola/zola/issues/32

To be honest on a choice of alternate format, I wouldn't really add rst if I had the choice, AsciiDoc does seem superior but it doesn't have a parser in Rust either. The implementation in Zola would have to come from someone other than me as well as this is a huge change that I wouldn't really use myself.

**Comment by polyzen** [comment] 2019-03-21 09:09
> I don't think this crate is an useable state.

Doesn't seem so:
https://github.com/flying-sheep/rust-rst/issues/4
https://github.com/flying-sheep/rust-rst/search?q=TODO&unscoped_q=TODO

> AsciiDoc does seem superior

rST seems vastly more popular, but I'm biased being such a big fan. Will have to take a closer look at AsciiDoc.

**Comment by Keats** [comment] 2019-03-21 09:12
> Doesn't seem so:

The last version on crates.io is 3 years old and even master doesn't have docs for the library itself so as a user it isn't useable.

**Comment by LuoZijun** [comment] 2019-03-22 13:17
reStructuredText 支持的特性其实更多，并且有一个统一完整的标准和规范。

相比较来讲，Markdown 的规范则很分散，并且也不太完整。比如 `contents` 这样的特性，或者是一些 `Metadata` 之类的，都需要你自己重新定义和实现（比如这个项目里面使用 `+++ ... +++` 来实现一个 `Metadata` ）。


reStructuredText supports more features and has a unified and complete standard and specification. By comparison, the Markdown specification is fragmented and less complete.

Features like ' contents ', or something like ' Metadata ', need to be redefined and implemented yourself (such as the use of ' + + + ... + + + ' in this project to achieve a ' Metadata '). 

-- From Bing Translate

**Comment by Keats** [comment] 2019-03-26 18:00
I moved the feature request to the forum: https://zola.discourse.group/t/alternative-input-formats/76

**Closed as completed by Keats** 2019-03-26 18:00 UTC

**Comment by piedoom** [comment] 2019-03-26 19:21
just a heads up that discourse provides a [voting plugin for feature requests which might interest you.](https://github.com/discourse/discourse-voting)
