### ISSUE TITLE
support for YAML frontmatters

### ISSUE THREAD

**Issue by mash-graz** [getzola/zola#498] opened 2018-10-25 04:42 UTC
gutenberg seems to support only TOML frontmatters right now.

i try to use it with [netlify-cms](https://www.netlifycms.org), which should [support different kinds of frontmatter formats and their common delimiters](https://www.netlifycms.org/docs/configuration-options/#extension-and-format), but unfortunately this doesn't work very well and retaining its default YAML preferences would make everything much easier. what's even more annoying, is the fact, that GitLabs markdown renderer also doesn't like TOML frontmatters. :(

i really think, it would be a valuable improvement, if gutenberg would support other kinds of frontmatter formats as well to become more compatible to other SSGs and workflows.

**Comment by Keats** [comment] 2018-10-25 07:12
Duplicate of https://github.com/Keats/gutenberg/issues/317

I'm really not a fan of YAML and there is no good safe yaml library in Rust I believe.

**Closed as completed by Keats** 2018-10-25 07:12 UTC

**Comment by piedoom** [comment] 2018-10-25 14:46
@mash-graz I've had success with netlify-cms + gutenberg.  I have my code here if you'd like to take a look https://github.com/U9H/newsletter

**Comment by mash-graz** [comment] 2018-10-25 19:38
> I've had success with netlify-cms + gutenberg. I have my code here if you'd like to take a look https://github.com/U9H/newsletter

thanks for this very instructive example!

but unfortunately it does show on GitHub exactly the same issues as my project at GitLab:

frontmatters using TOML look very uggly in the markdown preview of both platforms, but YAML frontmatters would be rendered in a much more pretty and useful way. 

as you didn't use a standard markdown image embedding syntax, i can just guess, that this feature will most likely also show the same issues on both platforms.

**Comment by cup** [comment] 2020-01-17 03:10
https://github.com/getzola/zola/issues/189
https://github.com/getzola/zola/issues/317

https://github.com/getzola/zola/issues/498
