### ISSUE TITLE
Inline CSS

### ISSUE THREAD

**Issue by shalzz** [getzola/zola#605] opened 2019-02-01 16:45 UTC
# Bug Report

## Environment

Zola version: 0.5.1

## Expected Behavior
Ability to inline CSS in a document. This helps with critical CSS that should be loaded with the main document and makes sure the render/paint time of a page is not held up while separately loading a CSS file.

## Current Behavior
No way to inline CSS

**Comment by Keats** [comment] 2019-02-01 18:33
How would that look?

**Comment by shalzz** [comment] 2019-02-02 04:55
A function like `get_css` or maybe extend `load_data` to work with `.css` files so that one can get the contents of the file into a buffer and use it in a template like so:
```django
{% set css = load_data(path="critical.css") %}
<style>{{ css }}</style>
```

**Comment by Keats** [comment] 2019-02-02 10:53
`load_data` should load that css as plain text no? I haven't used it yet but that's what I remember from the review

**Comment by shalzz** [comment] 2019-02-02 11:45
That'd only work with css files in static/ right? I haven't tried because I'm using .sass files compiled to .css files and ideally have something that hooks into that system and gives you a buffer of the final output/file.

**Comment by Keats** [comment] 2019-02-04 18:55
`.sass` files will get compiled in the static folder so yeah `load_data` should work there.

I don't think it would make sense to hook the Sass compilation with the templating, you wouldn't get live reload anyway.

**Comment by shalzz** [comment] 2019-02-05 03:10
Huh.. For me the `.sass` compiles into the root of the public directory.
Trying to do this with `even` theme doesn't build:
https://github.com/shalzz/even/commit/ccda2fb9836c552e5ac0069ca6adf132e39ff6ae

**Comment by Keats** [comment] 2019-02-05 10:07
Sorry I meant public not static.
I'll have a look later, I thought it would work out of the box

**Comment by Keats** [comment] 2019-02-09 20:02
So the reason it is not working is that `load_path` defaults to `content/` for the base directory...
That does seem like a valid use of `load_data` though and I would prefer not having too many Tera functions.

What do you think @kellpossible ?

**Comment by ryanmcgrath** [comment] 2019-03-08 23:19
FWIW, `load_data` works fine with relative paths - I use it for exactly this reason (along with loading some JSON to render into a template).

e.g, just `{% set css = load_data(path="../das/path/etc") %}`

**Comment by Keats** [comment] 2019-03-09 08:38
Maybe the default folder should be the `base_path`? To avoid having to use `..`

**Comment by ryanmcgrath** [comment] 2019-03-09 21:51
Base path would make more sense to me, and I recall wondering why it wasn’t that...

**Comment by shalzz** [comment] 2019-03-10 03:33
> FWIW, `load_data` works fine with relative paths - I use it for exactly this reason (along with loading some JSON to render into a template).
> 
> e.g, just `{% set css = load_data(path="../das/path/etc") %}`

Sure relative paths work but the css file should exits before we try to load it. The problem here is with css files compiled from sass.

try building this with your example: https://github.com/shalzz/even/commit/533d25b300a21ed2f0b1c92010ab561dae23a218
you'd get this:
```
$ zola build
Building site...
-> Creating 15 pages (0 orphan), 1 sections, and processing 0 images
Failed to build the site
Error: Failed to render page '/tmp/even/content/pages/about.md'
Reason: Failed to render 'about.html' (error happened in a parent template)
Reason: /tmp/even/content/../public/site.css doesn't exist
```

**Comment by Keats** [comment] 2019-03-11 19:25
> Base path would make more sense to me, and I recall wondering why it wasn’t that...

That's now the case in `next`.

> Sure relative paths work but the css file should exits before we try to load it.

It should be fixed in `next` as well, all assets are now generated/copied before rendering templates.

**Comment by Keats** [comment] 2019-03-22 19:44
@shalzz your repo is now working with the `next` branch!

**Closed as completed** 2019-03-25 19:59 UTC
Labels: enhancement

**Comment by foray1010** [comment] 2019-05-22 12:45
fyi, I have to use `<style>{{ css | safe }}</style>` instead because I used `/` in css which is escaped by default

**Comment by Keats** [comment] 2019-05-22 13:03
Yeah... It would be great to have the concept of MarkupSafe strings in Tera but I'm not sure how to do that (yet). In the meantime, you can use `| safe` on pretty much everything from Zola.

**Comment by vimpostor** [comment] 2023-12-22 01:43
> In the meantime, you can use `| safe` on pretty much everything from Zola.

I have a feeling `| safe` is not entirely sufficient, it still seems to be turning all my `::` into `:`, which is not necessarily semantically identical, e.g. `li.title-list::marker` -> `li.title-list:marker`.

Is there a way to fix inline css for those cases? Ironically if I drop the `| safe`, then the `::` works again, but of course other stuff is broken.

**Comment by Keats** [comment] 2023-12-22 08:54
Escaping should not touch `:` 🤔

**Comment by vimpostor** [comment] 2023-12-22 12:41
Ah I think it's not `| safe` who is at fault here, but the general evaluation function. Minimal reproducable example:
```
<style>{{"li::marker {}"}}</style>
<!-- also not working -->
<style>{{"li::marker {}" | safe}}</style>
```

Note the `{{}}` wrapper, the problem does not happen if I use a plain string.

Here the `::` turns into `:`, but that is not allowed here, because [::marker](https://developer.mozilla.org/en-US/docs/Web/CSS/::marker) must be a pseudo-element.

Is this a zola bug or should I report the problem at tera?

**Comment by Keats** [comment] 2023-12-22 13:23
Can you open a new issue?

**Comment by vimpostor** [comment] 2023-12-22 14:51
Turns out, it only happens when `minify_html` is true and the problem is already reported at the end of the dependency chain zola -> minify-html -> css-minify here: https://github.com/Mnwa/css-minify/issues/6
