### ISSUE TITLE
Inconsistent replacement of _ with -

### ISSUE THREAD

**Issue by ad-si** [getzola/zola#832] opened 2019-10-29 09:47 UTC
# Bug Report

When I have a directory
```txt
content
  |- dir_with_underscore
    |- a.md
    |- b.md
    |- index.md
```

it builds it in following way:

```txt
content
  |- dir-with-underscore
    |- index.md
  |- dir_with_underscore
    |- a.md
    |- b.md
```

## Environment

Zola version: 0.9.0

## Expected Behavior

```txt
content
  |- dir-with-underscore
    |- index.md
    |- a.md
    |- b.md
```

Actually, I would expect it to keep the underscore!?

**Comment by Keats** [comment] 2019-10-29 09:49
Duplicate of https://github.com/getzola/zola/issues/768 that has now a pretty huge scope

**Closed as completed by Keats** 2019-10-29 09:49 UTC
