### ISSUE TITLE
While scaling image zola shows "processing 0 images"

### ISSUE THREAD

**Issue by rootkea** [getzola/zola#1504] opened 2021-05-30 16:14 UTC
Hello!

Steps to reproduce:
1. Place sunset.jpg at `content/foo`
2. Create an HTML template containing this `resize_image()` call
  ```
  <img src="{{resize_image(path="foo/sunset.jpg", width=150, height=150, op="scale")}}" />
  ``` 
3. Remove processed images
  ```
  $ rm -rf static/processed_images/
  ```
4. Build site
  ```
  $ ../zola/target/debug/zola build
  Building site...
  Checking all internal links with anchors.
  > Succesfully checked 0 internal link(s) with anchors.
  -> Creating 11 pages (0 orphan), 4 sections, and processing 0 images
  ```

Says "processing 0 images" but generates an image at `static/processed_images/`

**Comment by Keats** [comment] 2021-05-30 16:16
This part is being rewritten so it's probably going to be fixed but keeping it open for now.

**Comment by rootkea** [comment] 2021-05-30 16:20
Ah, also next branch takes 40 times more time than 0.13.0 to build the same site. Maybe it's related to ongoing work too? OR should I open a fresh issue for it?
1. zola 0.13.0      "Done in 1.5s."
2. zola next         "Done in 72.6s."

Looks like image processing is taking much more time on zola next.

**Comment by Keats** [comment] 2021-05-30 16:22
Did you build with `--release`? The changes have not been merged yet

**Comment by rootkea** [comment] 2021-05-30 16:23
1. For 0.13.0 I downloaded the release binaries
2. For zola next I checked out next branch and then did `cargo build`

Edit - Building with `--release` now...

**Comment by Keats** [comment] 2021-05-30 16:32
Do `cargo build --release`. Non-release builds of Rust programs are very slow in exchange of faster compile times

**Comment by rootkea** [comment] 2021-05-30 17:02
I built with `--release`.  The zola build took more time than without `--release` but didn't improve zola next site build time.
```
$ rm -rf static/processed_images/
$ ../zola/target/debug/zola build
Building site...
Checking all internal links with anchors.
> Succesfully checked 0 internal link(s) with anchors.
-> Creating 11 pages (0 orphan), 4 sections, and processing 0 images
Done in 75.2s.

$ rm -rf static/processed_images/
$ zola build
Building site...
-> Creating 11 pages (0 orphan), 4 sections, and processing 0 images
Done in 1.7s.

$
```

**Comment by rootkea** [comment] 2021-05-30 17:09
Even when there is no image processing, zola next is way slow than zola 0.13.0
After commenting out `resize_image()`:
```
$ rm -rf static/processed_images/
$ ../zola/target/debug/zola build
Building site...
Checking all internal links with anchors.
> Succesfully checked 0 internal link(s) with anchors.
-> Creating 11 pages (0 orphan), 4 sections, and processing 0 images
Done in 5.0s.

$ rm -rf static/processed_images/
$ zola build
Building site...
-> Creating 11 pages (0 orphan), 4 sections, and processing 0 images
Done in 163ms.

$
```

**Comment by Keats** [comment] 2021-05-30 18:01
/zola/target/debug/zola build


Means you are running the debug version. The release one will be at
target/release/zola

**Comment by rootkea** [comment] 2021-05-30 19:17
Oh man! Feeling so embarrassed.

Indeed `target/release/zola` gives nearly same site build times as that of zola 0.13.0.

Thanks!

**Comment by rootkea** [comment] 2021-05-31 04:51
On a related note, should we add build instructions to `README.md` like other projects:

## Build
```
$ cargo build --release
$ target/release/zola -V
```

**Comment by Keats** [comment] 2021-06-24 20:26
@rootkea are you still getting the 0 image message on `next`?

Edit: nevermind, just saw it happen.

**Comment by Keats** [comment] 2021-06-24 21:37
Ok so the issue is that this image is shown before we are actually rendering the templates so we don't know whether we have anything to do. I would be inclined to remove that part of the message. What do you think @vojtechkral ?

**Comment by vojtechkral** [comment] 2021-06-24 22:38
Yeah, probably. Maybe it would be better to add a message later on when the imageproc is launched, but I don't have any strong feelings about that...

**Closed as completed** 2021-12-05 19:55 UTC
Labels: bug, done in pr

**Comment by rootkea** [comment] 2021-12-20 14:58
> Maybe it would be better to add a message later on when the imageproc is launched

Yes please. I think number of images being/been processed is an important stat (like no. of pages and sections created).

This issue was regarding the incorrect stat value shown for `scale` op. If I remember correctly, the number of images processed was shown correctly for other image processing ops.

**Comment by Keats** [comment] 2021-12-20 19:38
> If I remember correctly, the number of images processed was shown correctly for other image processing ops.

All ops are done after iirc
