### ISSUE TITLE
Zola unable to markdown relative links that are not in page.content

### ISSUE THREAD

**Issue by crzysdrs** [getzola/zola#1316] opened 2021-01-19 01:40 UTC
# Bug Report

## Environment

Zola version: 0.13.0

## Expected Behavior
Zola should be able to `markdown` internal links that come from other fields besides the `page.content`.

## Current Behavior

If an internal link is in field that is converted via `markdown` (that is not `page.content`), zola is unable to find the corresponding internal link.
```
$ zola serve
Building site...
-> Creating 2 pages (0 orphan), 0 sections, and processing 0 images
Error: Failed to render page '/home/crzysdrs/proj/zola_test/content/1.md'
Reason: Failed to render 'page.html'
Reason: Filter call 'markdown' failed
Reason: Failed to render markdown filter: Error { kind: Msg("Relative link @/2.md not found."), source: None }
```

## Step to reproduce

```
======= ./config.toml =======
title= "Test"
base_url = "/"

======= ./templates/page.html =======
{{ page.content | safe }}

{{ page.extra.md | markdown | safe }} {# FAILS #}

======= ./content/2.md =======
---
title: 2
extra:
    md: ""
---

======= ./content/1.md =======
---
title: "1"
extra:
    md : "[Page 2](@/2.md)"
---

[Page 2](@/2.md)
```

`zola build`

**Comment by southerntofu** [comment] 2021-01-19 21:24
Hi @crzysdrs am i correct that this bug is a duplicate of #1296? If so i just proposed a patch at #1318 feel free to take a look there see if it's good for you :)

**Comment by crzysdrs** [comment] 2021-01-19 22:11
I agree, this is a duplicate. Surprised I didn't find your issue when I searched.

**Closed as completed** 2021-01-19 22:10 UTC
