### ISSUE TITLE
urlencoded protocol name in sitemap.xml and rss.xml

### ISSUE THREAD

**Issue by zdenek-crha** [getzola/zola#791] opened 2019-08-29 16:31 UTC
# Bug Report

## Environment

Zola version: 0.8.0

## Step to reproduce
```sh
$ zola init new_site
$ cd new_site
$ zola build
$ cat public/sitemap.xml
```

## Expected Behavior

```xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="https://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
        <url>
            <loc>https://example.com/</loc>
        </url>
</urlset>
```

## Current Behavior

Notice the `urlencode`-ed colon character in `<loc>` tag in `https://` protocol name.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="https://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
        <url>
            <loc>https%3A//example.com/</loc>
        </url>
</urlset>
```

## Notes

Similar happens when `generate_rss = true` is set in `config.toml`. All tags that use site url have protocol part of the url encoded and links won't work: `<link>, <guid>, <atom:link href="...">, ...`

I think that the issue is that `urlencode` filter does not handle actual URI differently from any data.

Could any of there be considered solution?
* Adding flag to `urlencode(uri=true)`  that to let it know that it is supposed to escape URI and therefore parse it and escape only relevant parts
* Adding special filter `uriencode` that would just do that

**Comment by Keats** [comment] 2019-08-29 16:39
This is a duplicate of #762 and is already already fixed in the `next` branch along with the namespace being incorrect.

**Closed as completed by Keats** 2019-08-29 16:39 UTC
