### ISSUE TITLE
How to ignore page on section?

### ISSUE THREAD

**Issue by fundon** [getzola/zola#867] opened 2019-12-03 12:38 UTC
Example:

```
content
├── 10-Habits-of-a-Happy-Node-Hacker-2016.md
├── _index.md
├── about.md
├── Async-Await-on-Rust.md
├── ES6-QuickStart-and-Tips.md
├── Install-Gogs-on-macOS.md
├── resume.md
├── Ubuntu-Setup.md
└── Using-Docker-Compose-in-Node.js-Project.md

```

I want to ignore `resume.md` page, dont set it to the root section's pages. 

I set the blew in `_index.md`, but no effect:

```
+++
sort_by = "date"
ignored_pages = ["resume.md"]
+++
```

**Comment by Keats** [comment] 2019-12-03 12:49
Kind of duplicate of https://github.com/getzola/zola/issues/836
I think putting it on the page front-matter rather than the section one scales better though.

**Comment by fundon** [comment] 2019-12-03 13:08
Waiting for this small feature!

**Comment by Keats** [comment] 2020-05-25 17:11
Closing in favour of #836

**Closed as completed by Keats** 2020-05-25 17:11 UTC
