### ISSUE TITLE
config.toml: Failed to parse `languages` default value

### ISSUE THREAD

**Issue by rootkea** [getzola/zola#1489] opened 2021-05-26 09:20 UTC
Hello!

As per https://www.getzola.org/documentation/getting-started/configuration/ `languages` can have default value as:
```
languages = []
```
But on latest `next` branch I get:
```
$ ../zola/target/debug/zola serve -O
Building site...
Error: invalid type: sequence, expected a map for key `languages` at line 156 column 1
$
```

**Comment by Keats** [comment] 2021-05-26 12:07
Duplicate of https://github.com/getzola/zola/issues/1490

**Comment by Keats** [comment] 2021-05-26 12:07
Ah also, the `next` branch docs haven't been updated for i18n yet since it's still a bit moving

**Closed as completed by Keats** 2021-05-26 12:07 UTC

**Comment by rootkea** [comment] 2021-05-26 12:33
FWIW, `languages = []` works in zola 0.13.0.
