### ISSUE TITLE
[Feature Request]Can init a new project in current directory

### ISSUE THREAD

**Issue by chawyehsu** [getzola/zola#637] opened 2019-03-21 05:44 UTC
I'm used to creating project within an existed folder:

```
$ yarn init
...
```

And I know I can provide a name outside the current directory, but I wonder if zola could handle this:

```
$ zola init
error: The following required arguments were not provided:
    <name>

USAGE:
    zola.exe init <name>

For more information try --help

$ zola init .
Failed to create the project
Error: Folder `.` already exists
```

**Comment by Keats** [comment] 2019-03-21 08:51
Duplicate of https://github.com/getzola/zola/issues/406

Would be awesome if someone were to implement what is mentioned in that

**Comment by Keats** [comment] 2019-03-26 18:03
Closing in favour of #406

**Closed as completed by Keats** 2019-03-26 18:03 UTC
Labels: enhancement

**Comment by WallyFrets** [comment] 2019-10-20 23:20
Ive set up Zola on ubuntu 18.04 studio  - Created  ~/ZOLA/fr1 directory  and other ~/ZOLA/prog1 
deleted these subdirectories and despite using snap uninstall and reinstall different directory structure  but in ZOLA init ( with or without different directories structs )  this error continues see below:
**Failed to create the project
Error: File exists (os error 17)**

**Comment by Keats** [comment] 2019-10-21 09:53
It is buggy, there is a PR in progress: https://github.com/getzola/zola/pull/815
