### ISSUE TITLE
`get_image_metadata` cannot load image files under `/static`

### ISSUE THREAD

**Issue by lo48576** [getzola/zola#911] opened 2020-01-04 18:42 UTC
# Bug Report

## Environment

Zola version: 0.9.0

## Expected Behavior
`get_image_metadata("foo.jpg")` successfully loads metadata of `static/foo.jpg` if there are no `content/foo.jpg`.

## Current Behavior
`get_image_metadata("foo.jpg")` complains "Reason: `get_image_meta`: Cannot find path: foo.jpg" even if there is `static/foo.jpg`.

## Step to reproduce
1. Put an image to `static` folder, e.g. `static/foo.jpg`.
    + There should be no files with the same path, e.g. `content/foo.jpg`.
2. Run `get_image_metadata(path="foo.jpg")` in a template.
    + Both local templates or theme templates are ok.
3. Run `zola build` or `zola serve`.
    + It fails with `` `get_image_meta`: Cannot find path: foo.jpg `` error.

## Additional info

I think the lines below should be changed in some way.

https://github.com/getzola/zola/blob/e194294664f651a16f66d2cc07c8c2a3638642f8/components/site/src/lib.rs#L529-L532

https://github.com/getzola/zola/blob/e194294664f651a16f66d2cc07c8c2a3638642f8/components/templates/src/global_fns/mod.rs#L167-L170

**Comment by Keats** [comment] 2020-01-26 01:53
Hmm that would be a breaking change :/ But it makes sense to be able to use it on assets from static I think

**Comment by jasikpark** [comment] 2020-03-15 17:06
perhaps just require a get_url() or “/static/foo.jpg” to differentiate?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jasikpark** [comment] 2020-03-15 17:06
perhaps just require a get_url() or “/static/foo.jpg” to differentiate?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jasikpark** [comment] 2020-03-15 17:07
perhaps just require a get_url() or “/static/foo.jpg” to differentiate?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by chris-morgan** [comment] 2020-03-18 09:11
Two related things:

1. `{{ get_image_metadata(path="../static/foo.jpg") }}` works, but `{{ get_url(path="../static/foo.jpg") }}` doesn’t strip the `../static/` bit.

2. `content/foo.jpg` actually doesn’t work anyway; `{{ get_image_metadata(path="foo.jpg") }}` works, but the image file is not copied. (Presumably because of how the front page is magic rather than being a normal section with an `_index.md` file—I consider this magic a grave error, incidentally—and it doesn’t copy files that it can’t associate with a section or page, which I think should either be allowed or should warn.) So if you want an image file in the root of the site, it *needs* to be in /static/ at present.

**Comment by Keats** [comment] 2020-03-18 09:26
For 2, the front page is not magic. It creates an empty section if there is no `_index.md` so the site renders fine but you can define your own `_index.md` without any issues: https://github.com/Keats/tera/blob/master/docs/content/_index.md
The issue is that assets are only copied from content when present in a colocated folder. Random files in the tree are ignored in any other cases, nothing to do with the index page and there are no concepts of sections with colocated assets currently.

**Comment by Keats** [comment] 2021-07-19 19:51
Should be fixed in 0.14.

**Closed as completed by Keats** 2021-07-19 19:51 UTC
Labels: Feedback wanted, Breaking change
