### ISSUE TITLE
Cachebusting breaks get_url for style.css

### ISSUE THREAD

**Issue by Darksonn** [getzola/zola#1595] opened 2021-08-22 12:52 UTC
## Environment

Zola version: built locally from commit [`f866e0b650ba940bb7b40d6c2612e6649214c5b9`](https://github.com/getzola/zola/commit/f866e0b650ba940bb7b40d6c2612e6649214c5b9)

## Expected Behavior

The `get_url` function should work regardless of whether or not cachebusting is enabled.

This issue is likely similar to #1416 but for a different kind of file.

## Current Behavior

I get this error:
```
Building site...
Warning: Highlight language text not found in blog/fractals-360/index.md
Warning: Highlight language fsharp not found in blog/newton-intro/index.md
Warning: Highlight language fsharp not found in blog/newton-intro/index.md
Warning: Highlight language fsharp not found in blog/newton-intro/index.md
Warning: Highlight language fsharp not found in blog/newton-intro/index.md
Checking all internal links with anchors.
> Successfully checked 0 internal link(s) with anchors.
-> Creating 7 pages (0 orphan), 1 sections, and processing 0 images
Error: Failed to render section '/home/alice/src/ryhl.io/content/_index.md'
Reason: Failed to render 'index.html'
Reason: Function call 'get_url' failed
Reason: `get_url`: Could not find or open file style.css
```

## Step to reproduce

Building the website found in https://github.com/Darksonn/ryhl.io at commit [`928158a`](https://github.com/Darksonn/ryhl.io/commit/928158a3d4de4f5185ee7dad3086557d3a387914) triggers this issue. If [`templates/index.html`](https://github.com/Darksonn/ryhl.io/blob/928158a3d4de4f5185ee7dad3086557d3a387914/templates/index.html#L14) is changed to disable cachebusting for the `style.css` file on line 14, then the compilation works fine and `get_url` generates the path `http://127.0.0.1:1111/style.css`.

**Comment by Keats** [comment] 2021-08-22 14:47
Duplicate of https://github.com/getzola/zola/issues/1570 which is already fixed in `next` afaik.

> The get_url function should work regardless of whether or not cachebusting is enabled.

I don't think so, the cachebusting uses the hash of the file. If there are no file, we can't cachebust so it errors.

**Closed as completed by Keats** 2021-08-22 14:47 UTC
