### ISSUE TITLE
Error: Change on X detected but there is already an `index.md` in the same folder

### ISSUE THREAD

**Issue by zesterer** [getzola/zola#551] opened 2018-12-07 19:22 UTC
# Bug Report

## Environment

Zola version: 0.5.0

## Expected Behavior

The website should have successfully rebuilt

## Current Behavior

The following error occurs (presumably caused by [this line](https://github.com/getzola/zola/blob/master/components/rebuild/src/lib.rs#L320)):

```
Change detected @ 2018-12-07 19:14:25
-> Content changed /home/foo/site/content/blog/test.md
Failed to build the site
Error: Change on "/home/foo/site/content/blog/test.md" detected but there is already an `index.md` in the same folder
```

Note that if I re-run `zola serve`, the site builds as expected with no errors - clearly this error is therefore not intended.

## Step to reproduce

- Create an `_index.md` within `blog/`

- Create a markdown file within the same directory.

- Save something to the markdown file while `zola serve` is running.

**Comment by Keats** [comment] 2018-12-11 18:34
Are you sure the first file is called `_index.md` and not `index.md`? Note the leading underscore. This error only happens in co-located assets folder that contain an `index.md` as described in https://www.getzola.org/documentation/content/overview/#assets-colocation

I can't reproduce it locally with your steps :/

**Comment by zesterer** [comment] 2018-12-11 18:39
Absolutely certain. I'll do a little more testing when I get time.

**Comment by Keats** [comment] 2018-12-11 18:42
You can try running the documentation site of zola, it uses the same setup as your steps roughly. If you manage to reproduce it, can you share a minimal version?

**Comment by Keats** [comment] 2019-03-25 20:02
I can't reproduce that on 0.6.0 so closing for now.
If you have a reproduction for 0.6.0, please re-open!

**Closed as completed by Keats** 2019-03-25 20:02 UTC
