### ISSUE TITLE
Changing title of a section in _index.md does not rebuild TOC

### ISSUE THREAD

**Issue by PhilipDaniels** [getzola/zola#242] opened 2018-02-26 20:56 UTC
During serve.

If I change the title of a section in an `_index.md` page Gutenberg detects this and re-renders the page, but the title in the table of contents is not updated so they get out of sync. Restarting Gutenberg fixes it.

**Comment by Keats** [comment] 2018-03-01 14:04
I can't reproduce that, it livereloads just fine for me. Do you have an example site for the issue?

**Comment by PhilipDaniels** [comment] 2018-03-01 20:08
Happens for me with https://github.com/PhilipDaniels/rsforcs

You will need to work on your next branch because I have changed the highlight theme to one that was in my recent PR. If I edit the title in `site/content/introduction/_index.md` which is currently as follows, then I get the observed behaviour.

```
+++
title = "Introduction"
weight = 10
sort_by = "weight"
+++
```

**Comment by Keats** [comment] 2018-03-03 19:24
Ok that's a bit of a particular case using some kind of menu like that. The live reloader tries to do the least possible but in that repo case it would need to render the whole site again to live reload properly. I don't really want to rebuild the whole site on any change as it would be potentially slow and overkill for most sites so I would say it's acceptable right now.

**Comment by Keats** [comment] 2018-03-18 08:48
Closing for now, might be revived if someone has a good idea or we decide to just reload the whole thing.

**Closed as completed by Keats** 2018-03-18 08:48 UTC
Labels: bug
