### ISSUE TITLE
slug doesn't preserve character case

### ISSUE THREAD

**Issue by kellpossible** [getzola/zola#841] opened 2019-11-06 14:07 UTC
# Bug Report

## Environment

Zola version: 0.9.0
OS: Linux

## Expected Behavior
with `/content/section/SomePage/index.md` containing:

```md
+++
title = "Some Page"
date = ...
slug = "SomePage"
+++
```

expected page url to be `/content/section/SomePage/`

## Current Behavior
page url is is `/content/section/somepage/`

**Comment by Keats** [comment] 2019-11-06 14:08
Duplicate of https://github.com/getzola/zola/issues/768

**Closed as completed by Keats** 2019-11-06 14:08 UTC
